# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "quiet"
    "splash"
    "video=DP-3:2560x1080@60"
    "video=DP-1:1920x1080@144"
    "video=DP-2:1920x1080@60"
    "mitigations=off"
    "loglevel=3"
    "usbcore.autosuspend=-1"
    "spec_store_bypass_disable=prctl"
    "spectre_v2=off"
    "iommu=pt"
    "amd_iommu=on"
    "rd.systemd.show_status=auto"
    "rd.udev.log_priority=3"
    "nowatchdog"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0f53e6a2-ecc0-4f6e-805b-fde86ac4d67d";
    fsType = "ext4";
  };

  fileSystems."/giardino" = {
    device = "/dev/disk/by-uuid/f08d0bb3-ac20-4936-a518-b60b61ad94e7";
    fsType = "ext4";
  };

  fileSystems."/orfeo" = {
    device = "/dev/disk/by-uuid/49bc237a-bf72-4d17-be82-66ad05a3ac2b";
    fsType = "ext4";
    # options = ["mode=777"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AE80-D3B1";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/08697725-d808-4429-a7ea-468f76ff43a5"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
