require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.whichkey" -- revisar
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.harpoon"
spec "user.neotest"
spec "user.autopairs"
spec "user.autotag"
spec "user.neogit"
spec "user.alpha"
spec "user.project"
spec "user.indentline"
spec "user.toggleterm"
spec "user.copilot"
spec "user.neoscroll"
spec "user.eyeliner"
spec "user.neotab"
spec "user.bufferline"
spec "user.cybu"

require "user.lazy"
